/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioBrainRouteImport } from './routes/studio.brain'
import { Route as StudioClientIdRouteImport } from './routes/studio.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioBrainRoute = StudioBrainRouteImport.update({
  id: '/studio/brain',
  path: '/studio/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioClientIdRoute = StudioClientIdRouteImport.update({
  id: '/studio/$clientId',
  path: '/studio/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio/$clientId': typeof StudioClientIdRoute
  '/studio/brain': typeof StudioBrainRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio/$clientId': typeof StudioClientIdRoute
  '/studio/brain': typeof StudioBrainRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio/$clientId': typeof StudioClientIdRoute
  '/studio/brain': typeof StudioBrainRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studio/$clientId' | '/studio/brain' | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio/$clientId' | '/studio/brain' | '/studio'
  id: '__root__' | '/' | '/studio/$clientId' | '/studio/brain' | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioClientIdRoute: typeof StudioClientIdRoute
  StudioBrainRoute: typeof StudioBrainRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/brain': {
      id: '/studio/brain'
      path: '/studio/brain'
      fullPath: '/studio/brain'
      preLoaderRoute: typeof StudioBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$clientId': {
      id: '/studio/$clientId'
      path: '/studio/$clientId'
      fullPath: '/studio/$clientId'
      preLoaderRoute: typeof StudioClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioClientIdRoute: StudioClientIdRoute,
  StudioBrainRoute: StudioBrainRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
